
// Cap the damage resistance to 75, 85 if barbarian

// ACTION_IF NOT FILE_EXISTS ~override/tb#resisttweak.txt~ THEN
// 	BEGIN
// 	COPY_EXISTING ~sw1h01.itm~ ~override/tb#resisttweak.txt~
// 	COPY ~refinements/armor/copy~ ~override~
// 	EXTEND_TOP ~baldur.bcs~ ~refinements/armor/baldur.baf~
// 	ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN
// 		BEGIN
// 		EXTEND_TOP ~baldur25.bcs~ ~refinements/armor/baldur.baf~
// 		END
// 	END

// Install ToBEx
ACTION_IF ENGINE_IS ~SOA TOB~ THEN BEGIN
 ACTION_IF (FILE_EXISTS ~bgmain.exe~) THEN BEGIN
  OUTER_SPRINT TOBEX_MOD_DIRECTORY "./refinements"
  LOAD_TRA "%TOBEX_MOD_DIRECTORY%/TobEx_redist/TobEx.tra"
  ACTION_INCLUDE "%TOBEX_MOD_DIRECTORY%/TobEx_redist/TobEx.tpa"
 END
END 

APPEND ~stats.ids~ ~128 WIZARD_PROTECTION_FROM_MAGIC_WEAPONS~
UNLESS ~WIZARD_PROTECTION_FROM_MAGIC_WEAPONS~
// emulates Detectable spells

APPEND ~class.ids~ ~202 LONG_BOW~ UNLESS ~LONG_BOW~
// since some mods remove this line and I decompiled in environment with LONG_BOW

APPEND ~GTIMES.IDS~ ~6 ONE_ROUND~ UNLESS ~ONE_ROUND~
APPEND ~GTIMES.IDS~ ~12 TWO_ROUNDS~ UNLESS ~TWO_ROUNDS~
APPEND ~GTIMES.IDS~ ~18 THREE_ROUNDS~ UNLESS ~THREE_ROUNDS~
APPEND ~GTIMES.IDS~ ~24 FOUR_ROUNDS~ UNLESS ~FOUR_ROUNDS~
APPEND ~GTIMES.IDS~ ~30 FIVE_ROUNDS~ UNLESS ~FIVE_ROUNDS~
APPEND ~GTIMES.IDS~ ~36 SIX_ROUNDS~ UNLESS ~SIX_ROUNDS~
APPEND ~GTIMES.IDS~ ~42 SEVEN_ROUNDS~ UNLESS ~SEVEN_ROUNDS~
APPEND ~GTIMES.IDS~ ~48 EIGHT_ROUNDS~ UNLESS ~EIGHT_ROUNDS~
APPEND ~GTIMES.IDS~ ~54 NINE_ROUNDS~ UNLESS ~NINE_ROUNDS~
APPEND ~GTIMES.IDS~ ~60 TEN_ROUNDS~ UNLESS ~TEN_ROUNDS~
APPEND ~GTIMES.IDS~ ~60 ONE_TURN~ UNLESS ~ONE_TURN~
APPEND ~GTIMES.IDS~ ~120 TWO_TURNS~ UNLESS ~TWO_TURNS~
APPEND ~GTIMES.IDS~ ~180 THREE_TURNS~ UNLESS ~THREE_TURNS~
APPEND ~GTIMES.IDS~ ~240 FOUR_TURNS~ UNLESS ~FOUR_TURNS~
APPEND ~GTIMES.IDS~ ~300 FIVE_TURNS~ UNLESS ~FIVE_TURNS~
APPEND ~GTIMES.IDS~ ~300 ONE_HOUR~ UNLESS ~ONE_HOUR~
APPEND ~GTIMES.IDS~ ~360 SIX_TURNS~ UNLESS ~SIX_TURNS~
APPEND ~GTIMES.IDS~ ~420 SEVEN_TURNS~ UNLESS ~SEVEN_TURNS~
APPEND ~GTIMES.IDS~ ~480 EIGHT_TURNS~ UNLESS ~EIGHT_TURNS~
APPEND ~GTIMES.IDS~ ~540 NINE_TURNS~ UNLESS ~NINE_TURNS~
APPEND ~GTIMES.IDS~ ~600 TEN_TURNS~ UNLESS ~TEN_TURNS~
APPEND ~GTIMES.IDS~ ~600 TWO_HOURS~ UNLESS ~TWO_HOURS~
APPEND ~GTIMES.IDS~ ~900 FIFTEEN_TURNS~ UNLESS ~FIFTEEN_TURNS~
APPEND ~GTIMES.IDS~ ~900 THREE_HOURS~ UNLESS ~THREE_HOURS~
APPEND ~GTIMES.IDS~ ~1200 FOUR_HOURS~ UNLESS ~FOUR_HOURS~
APPEND ~GTIMES.IDS~ ~1500 FIVE_HOURS~ UNLESS ~FIVE_HOURS~
APPEND ~GTIMES.IDS~ ~1800 SIX_HOURS~ UNLESS ~SIX_HOURS~
APPEND ~GTIMES.IDS~ ~2100 SEVEN_HOURS~ UNLESS ~SEVEN_HOURS~
APPEND ~GTIMES.IDS~ ~2400 EIGHT_HOURS~ UNLESS ~EIGHT_HOURS~
APPEND ~GTIMES.IDS~ ~2700 NINE_HOURS~ UNLESS ~NINE_HOURS~
APPEND ~GTIMES.IDS~ ~3000 TEN_HOURS~ UNLESS ~TEN_HOURS~
APPEND ~GTIMES.IDS~ ~3300 ELEVEN_HOURS~ UNLESS ~ELEVEN_HOURS~
APPEND ~GTIMES.IDS~ ~3600 TWELVE_HOURS~ UNLESS ~TWELVE_HOURS~
APPEND ~GTIMES.IDS~ ~7200 ONE_DAY~ UNLESS ~ONE_DAY~
APPEND ~GTIMES.IDS~ ~14400 TWO_DAYS~ UNLESS ~TWO_DAYS~
APPEND ~GTIMES.IDS~ ~21600 THREE_DAYS~ UNLESS ~THREE_DAYS~
APPEND ~GTIMES.IDS~ ~28800 FOUR_DAYS~ UNLESS ~FOUR_DAYS~
APPEND ~GTIMES.IDS~ ~36000 FIVE_DAYS~ UNLESS ~FIVE_DAYS~
APPEND ~GTIMES.IDS~ ~43200 SIX_DAYS~ UNLESS ~SIX_DAYS~
APPEND ~GTIMES.IDS~ ~50400 SEVEN_DAYS~ UNLESS ~SEVEN_DAYS~
APPEND ~GTIMES.IDS~ ~57600 EIGHT_DAYS~ UNLESS ~EIGHT_DAYS~
APPEND ~GTIMES.IDS~ ~64800 NINE_DAYS~ UNLESS ~NINE_DAYS~
APPEND ~GTIMES.IDS~ ~72000 TEN_DAYS~ UNLESS ~TEN_DAYS~
APPEND ~GTIMES.IDS~ ~79200 ELEVEN_DAYS~ UNLESS ~ELEVEN_DAYS~
APPEND ~GTIMES.IDS~ ~86400 TWELVE_DAYS~ UNLESS ~TWELVE_DAYS~
APPEND ~GTIMES.IDS~ ~93600 THIRTEEN_DAYS~ UNLESS ~THIRTEEN_DAYS~
APPEND ~GTIMES.IDS~ ~100800 FOURTEEN_DAYS~ UNLESS ~FOURTEEN_DAYS~
APPEND ~GTIMES.IDS~ ~108000 FIFTEEN_DAYS~ UNLESS ~FIFTEEN_DAYS~
APPEND ~GTIMES.IDS~ ~216000 THIRTY_DAYS~ UNLESS ~THIRTY_DAYS~
APPEND ~GTIMES.IDS~ ~360000 FIFTY_DAYS~ UNLESS ~FIFTY_DAYS~
// auto-extracted by Excel, didn't type them! same reason as above

// ADD_SECTYPE ~TB#Paladinhood~ ~Lost virtuous abilities~
// ADD_SECTYPE ~TB#SecondWind~ ~Second Wind triggered~

// ~Fix~ to the meteor swarm projectile.
COPY_EXISTING ~metswarm.pro~ ~override~
  WRITE_LONG 0x104 ~0x0000000000000000~
  WRITE_LONG 0x108 ~0x0000000000000000~

// LI#BARD1 is for all bards, excluding jesters. Also used by Greater War Cry.
// LI#BARD2 is for Jesters. Also used by Death Field.
// TG#ENES2 is used by Energy Storm. Also used by Druids' Whirlwind.
// TG#HOLA  is used by Holy Aura. Also used by Union.
ADD_PROJECTILE      ~refinements/Hlab/_pro/TG#SHOC.PRO~
ADD_PROJECTILE      ~refinements/Hlab/_pro/TG#TOXT.PRO~
ADD_PROJECTILE      ~refinements/Hlab/_pro/TG#ENES2.PRO~
ADD_PROJECTILE      ~refinements/Hlab/_pro/TG#ENES3.PRO~
ADD_PROJECTILE      ~refinements/Hlab/_pro/LI#BARD1.PRO~
ADD_PROJECTILE      ~refinements/Hlab/_pro/LI#BARD2.PRO~
ADD_PROJECTILE      ~refinements/Hlab/_pro/TG#HOLA.PRO~

// New portrait icons!
// Includes the fix for Spell Shield! The two corrected spells are in the
// ~refinements/Hlab/_shared/copy~ folder.
// COPY ~refinements/Hlab/_shared/STATDESC.2DA~     ~override/STATDESC.2DA~

ACTION_IF GAME_IS ~tob bgt~ BEGIN
 COPY ~refinements/Hlab/_shared/states.bam~ ~override~
 COPY ~refinements/Hlab/_shared/states2.bam~ ~override~
 APPEND  ~STATDESC.2DA~ ~166     AQUA
167     IDOL
168     SPIRF
169     SCION
170     CHANT
171     DRAGF
172     TIGS
173     CHANM
174     CRIPP
175     DIVSH
176     ENDU
177     GUARD
178     EXOR
179     LING
180     PREC
181     MERC
182     SPII
183     TKAI
184     SECW
185     INTI
186     AEGI
187     SHOL
188     FORS~
 COPY_EXISTING ~STATDESC.2DA~     ~override/STATDESC.2DA~
  REPLACE ~63873~   @274
  REPLACE ~AQUA~    @414
  REPLACE ~IDOL~    @400
  REPLACE ~SPIRF~   @408
  REPLACE ~SCION~   @416
  REPLACE ~CHANT~   @186
  REPLACE ~DRAGF~   @180
  REPLACE ~TIGS~    @182
  REPLACE ~CHANM~   @422
  REPLACE ~CRIPP~   @141
  REPLACE ~DIVSH~   @152
  REPLACE ~ENDU~    @212
  REPLACE ~GUARD~   @484
  REPLACE ~EXOR~    @120
  REPLACE ~LING~    @176
  REPLACE ~PREC~    @462
  REPLACE ~MERC~    @1016
  REPLACE ~SPII~    @1012
  REPLACE ~TKAI~    @444
  REPLACE ~SECW~    @197
  REPLACE ~INTI~    @192
  REPLACE ~AEGI~    @130
  REPLACE ~SHOL~    @126
  REPLACE ~FORS~    @139
// S_2_E_L/N is slower with so small stuff
  SET_2DA_ENTRY  124   1   2 8286
  SET_2DA_ENTRY  74   1   2 26228
END

// Player's summoned critters in BP get their scripts changed.
// We don't want this to happen to *our* new precious scripts :)
// (Revised Celestials, Ancient Spirit, Elemental Princes)
ACTION_IF FILE_EXISTS_IN_GAME ~gb-summ.bcs~ THEN BEGIN
COPY_EXISTING_REGEXP GLOB ~gb-s.*\.bcs~ ~override~
  DECOMPILE_BCS_TO_BAF
    REPLACE_TEXTUALLY ~  !InParty(LastSeenBy(Myself))
  !Specifics(LastSeenBy(Myself),200)
  !Gender(LastSeenBy(Myself),MALE)
  !Gender(LastSeenBy(Myself),FEMALE)
  !Gender(LastSeenBy(Myself),ILLUSIONARY)
  !Allegiance(LastSeenBy(Myself),GOODBUTBLUE)
  !Allegiance(LastSeenBy(Myself),NEUTRAL)
  !Class(LastSeenBy(Myself),WIZARD_EYE)
  !HasItemEquiped("fammy",LastSeenBy(Myself))
  ~  ~!InParty(LastSeenBy(Myself))
  !Specifics(LastSeenBy(Myself),200)
  !Gender(LastSeenBy(Myself),MALE)
  !Gender(LastSeenBy(Myself),FEMALE)
  !Gender(LastSeenBy(Myself),ILLUSIONARY)
  !Allegiance(LastSeenBy(Myself),GOODBUTBLUE)
  !Allegiance(LastSeenBy(Myself),NEUTRAL)
  !Class(LastSeenBy(Myself),WIZARD_EYE)
  !HasItemEquiped("fammy",LastSeenBy(Myself))
  !HasItemEquiped("tg#solb",LastSeenBy(Myself))
  !HasItemEquiped("tg#plang",LastSeenBy(Myself))
  !HasItemEquiped("tg#devae",LastSeenBy(Myself))
  !HasItemEquiped("tg#devag",LastSeenBy(Myself))
  !HasItemEquiped("tg#spir",LastSeenBy(Myself))
  !HasItemEquiped("tg#benh",LastSeenBy(Myself))
  !HasItemEquiped("elemchan",LastSeenBy(Myself))
  !HasItemEquiped("elemsunn",LastSeenBy(Myself))
  !HasItemEquiped("elemzaam",LastSeenBy(Myself))
  ~
  COMPILE_BAF_TO_BCS
  END



/* shared files */

COPY ~refinements/Hlab/_anim~                   ~override~
COPY_EXISTING - ~xpcap.2da~   ~.../xpcap.2da~
                ~xplevel.2da~ ~.../xplevel.2da~
COPY ~refinements/Hlab/_shared/copy~            ~override~
COPY ~.../xpcap.2da~   ~override~
     ~.../xplevel.2da~ ~override~
COPY ~refinements/Hlab/_shared/TG#EVAS.SPL~     ~override/TG#EVAS.SPL~
SAY NAME1 @111
SAY NAME2 @111
SAY UNIDENTIFIED_DESC @112
COPY ~refinements/Hlab/_shared/LI#GCRY.SPL~     ~override/LI#GCRY.SPL~
WRITE_SHORT   0x98   ~%LI#BARD1%~
COPY ~refinements/Hlab/_shared/LI#SCR1.SPL~     ~override/LI#SCR1.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR2.SPL~     ~override/LI#SCR2.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR3.SPL~     ~override/LI#SCR3.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR4.SPL~     ~override/LI#SCR4.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR5.SPL~     ~override/LI#SCR5.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR6.SPL~     ~override/LI#SCR6.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR7.SPL~     ~override/LI#SCR7.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR8.SPL~     ~override/LI#SCR8.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR9.SPL~     ~override/LI#SCR9.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR10.SPL~     ~override/LI#SCR10.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR1B.SPL~     ~override/LI#SCR1B.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR3B.SPL~     ~override/LI#SCR3B.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR4B.SPL~     ~override/LI#SCR4B.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR5B.SPL~     ~override/LI#SCR5B.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR6B.SPL~     ~override/LI#SCR6B.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR7B.SPL~     ~override/LI#SCR7B.SPL~
SAY 0xce @113
SAY 0x12e @114
COPY ~refinements/Hlab/_shared/LI#SCR8B.SPL~     ~override/LI#SCR8B.SPL~
SAY 0xce @113
SAY 0x12e @114


COPY ~refinements/Hlab/_shared/LI#SCRB.SPL~     ~override/LI#SCRB.SPL~
SAY NAME1 @115
SAY NAME2 @115
SAY UNIDENTIFIED_DESC @116
COPY ~refinements/Hlab/_shared/TG#SCRB.SPL~     ~override/TG#SCRB.SPL~
SAY NAME1 @115
SAY NAME2 @115
SAY UNIDENTIFIED_DESC @117
COPY ~refinements/Hlab/_shared/LI#SCRT.SPL~     ~override/LI#SCRT.SPL~
SAY NAME1 @115
SAY NAME2 @115
SAY UNIDENTIFIED_DESC @118

COPY ~refinements/Hlab/_shared/SPCL917.SPL~     ~override/SPCL917.SPL~
SAY UNIDENTIFIED_DESC @119

/* New visuals for Whirlwinds and Smite. Dynamic code by the_bigg */

COPY_EXISTING ~spcl900.spl~ ~override~
               ~spcl901.spl~ ~override~
     READ_LONG 0x64 ext_off
     READ_LONG 0x6a eff_off
     READ_SHORT ext_off + 0x1e eff_cnt
     WRITE_SHORT ext_off + 0x1e eff_cnt + 1
     SET edit = 0
     WHILE (eff_cnt > 0) AND (edit = 0) BEGIN
           SET eff_cnt = eff_cnt - 1
           READ_SHORT eff_off + (eff_cnt * 0x30) opcode
           PATCH_IF opcode = 215 BEGIN
                    WRITE_BYTE eff_off + (eff_cnt * 0x30) + 2 1
                    WRITE_LONG eff_off + (eff_cnt * 0x30) + 8 1
                    WRITE_BYTE eff_off + (eff_cnt * 0x30) + 0xc 0
                    WRITE_BYTE eff_off + (eff_cnt * 0x30) + 0xe 1
                    WRITE_ASCII eff_off + (eff_cnt * 0x30) + 0x14 ~TG#WHIR1~
                    SET edit = 1
           END
     END
     INSERT_BYTES eff_off + ((eff_cnt + 1) * 0x30) 0x30
     SET copyloop = 0
     WHILE copyloop < 0x30 BEGIN
           READ_BYTE eff_off + (eff_cnt * 0x30) + copyloop copyme
           WRITE_BYTE eff_off + ((eff_cnt + 1) * 0x30) + copyloop copyme
           SET copyloop = copyloop + 1
     END
     WRITE_BYTE eff_off + ((eff_cnt + 1) * 0x30) + 0x1b 0x32 // 2 in ASCII


COPY_EXISTING ~spcl909.spl~ ~override~
    READ_LONG 0x64 ext_off
    READ_LONG 0x6a eff_off
    READ_SHORT ext_off + 0x1e eff_cnt
    SET edit = 0
    WHILE (eff_cnt > 0) AND (edit = 0) BEGIN
          SET eff_cnt = eff_cnt - 1
          READ_SHORT eff_off + (eff_cnt * 0x30) opcode
          PATCH_IF opcode = 215 BEGIN
                   WRITE_BYTE eff_off + (eff_cnt * 0x30) + 2 1
                   WRITE_LONG eff_off + (eff_cnt * 0x30) + 8 0
                   WRITE_ASCII eff_off + (eff_cnt * 0x30) + 0x14 ~SPGRWHRL~
                   SET edit = 1
          END
    END



/* Revised Celestials */
COPY ~refinements/Hlab/_celestials/_shared~     ~override~
COPY ~refinements/Hlab/_celestials/Deva~     ~override~
COPY ~refinements/Hlab/_celestials/Fallen Deva~     ~override~
COPY ~refinements/Hlab/_celestials/Fallen Planetar~     ~override~
COPY ~refinements/Hlab/_celestials/Fallen Solar~     ~override~
COPY ~refinements/Hlab/_celestials/Planetar~     ~override~
COPY ~refinements/Hlab/_celestials/Solar~     ~override~

COMPILE ~refinements/Hlab/_celestials/_scripts~ USING ~refinements/languages/%s/miscscripts.tra~



/* Shapeshifter/Blade handling */

INCLUDE ~refinements/lib/kit_ee.tpa~


/* Multiclasses */

COPY ~refinements/Hlab/Multiclass/copy~	         ~override~


/*
COPY_EXISTING ~LI#FLPA.SPL~ ~override~
WRITE_LONG 450 TB#Paladinhood

ACTION_IF !(FILE_EXISTS ~bgmain.exe~)
THEN BEGIN
    PRINT @524
END
*/


/*
COPY_EXISTING     ~LUABBR.2DA~                  ~override/LUABBR.2DA~
SET_2DA_ENTRY_LATER ~_#_#_#lua~  12   1 ~FMT~
SET_2DA_ENTRY_LATER ~_#_#_#lua~  17   1 ~FMC~
SET_2DA_ENTRIES_NOW ~_#_#_#lua~ 2 // don't pretty print the S_2_E_N/L since it's anyway 1 coloumn...
*/



